"""Render a GitHub PR comment from an EvolveReport."""

from __future__ import annotations

from typing import Any


def render_pr_comment(report: dict[str, Any], *, diff: dict[str, Any] | None = None) -> str:
    stab = (report.get("stability") or {}).get("composite")
    stage = (report.get("ecology") or {}).get("global_stage") or (report.get("phylogeny") or {}).get("current_stage")
    fat = (report.get("fatigue") or {}).get("fatigue_score")
    drift = (report.get("drift") or {}).get("global_drift")
    clades = (report.get("taxonomy") or {}).get("clades") or []
    risks = (report.get("risk") or {}).get("failure_points") or []
    top_risks = risks[:5]

    lines = [
        "## CodeEvolve evolutionary check",
        "",
        f"- **Stage:** `{stage}` · **Stability:** `{stab}` · **Fatigue:** `{fat}` · **Drift:** `{drift}`",
        f"- **Model tier:** `{report.get('model_tier', 'slm')}` · commits=`{report.get('commit_count')}`",
        "",
        "### Clades touched (top)",
    ]
    for c in clades[:6]:
        lines.append(
            f"- `{c.get('id')}` **{c.get('label')}** ({c.get('layer')}) — churn={c.get('churn')}"
        )
    lines += ["", "### Top failure points"]
    if not top_risks:
        lines.append("- None ranked")
    for w in top_risks:
        lines.append(
            f"- **{w.get('id')}** `{w.get('kind')}` ({w.get('severity')}) — `{w.get('path')}`"
        )

    if diff:
        lines += ["", "### Since last report"]
        for x in (diff.get("worsened") or [])[:6]:
            lines.append(f"- Worsened: {x}")
        for x in (diff.get("improved") or [])[:6]:
            lines.append(f"- Improved: {x}")
        if not diff.get("worsened") and not diff.get("improved"):
            lines.append("- No material metric deltas")

    lines += ["", "_Generated by [CodeEvolve](https://github.com/ehallford11714/codeevolve)_", ""]
    return "\n".join(lines)
